### ISSUE TITLE
Feat: 신청 완료 페이지

### ISSUE THREAD

**Issue by zwonkim** [KDT3-miniproject-team1/frontend#29]
## 목적
장바구니에서 신청이 완료되면 결제 완료 페이지로 넘어가게 만드는 건 어떨까요 ? 구매 api가 따로 없어서 구매한 내역을 확인할 수는 없지만 .. 그래도 신청이 완료되었다는 안내 페이지가 있으면 신청 여부를 확실하게 알 수 있을 것 같아서요 !

- [x] 신청완료 페이지 마크업

## 세부 내용
참고할 디자인은 요거구요 ! 주문번호는 uuid로 랜덤으로 뽑고 신청일자 정도 date로 뽑으면 괜찮지 않을까욥 ..?
![IMG_5973](https://user-images.githubusercontent.com/103507999/219398417-6a8d2818-f7d6-4389-a0fd-e3938f8d05b6.PNG)

**Comment by yujiseok** [comment]
오 이런 거 있으면 좋긴 할 거 같아요!
좀 더 있는 사이트 같을지도?!
